Blog/urls.py
from django.conf.urls import include, url
import xadmin

xadmin.autodiscover()
# version模块自动注册需要版本控制的 Model
from xadmin.plugins import xversion
xversion.register_models()

urlpatterns = (
    url(r'^xadmin', include(xadmin.site.urls)),
    # url(r'^search/', include('haystack.urls')),  # 全文检索
    url(r'^login/', include('social_django.urls', namespace='social')),  # 第三方登录
    url(r'^user/', include('apps.user.urls')),  # 用户模块
    url(r'', include('apps.blog.urls')),  # 博客模块
)

apps/blog/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [
    url(r'^about/$', view=about),         # 关于页面
    url(r'^blog/(\d+)/$', view=blog),     # 博客页面
    url(r'^contact/$', view=Contact),     # 联系页面
    url(r'^tags/(\d+)$', view=tags),      # 根据标签查询
    url(r'^classfiy/(\d+)', view=classfiy),   # 根据分类显示
    url(r'^tidy/(?P<year>[\d+]{4})/(?P<month>[\d+]{1,2})', view=tidy),  # 根据归档显示
    url(r'^contatc_post/$', view=contatc_post),  # 接收联系的数据
    url('(?P<pindex>\d*)|[/]', view=index),   # 显示博客首页
    url(r'\w+', view=not_found),              # 404页面
]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

extra_apps/social_django/urls.py
"""URLs module"""
from django.conf import settings
from django.conf.urls import url

from social_core.utils import setting_name
from . import views


extra = getattr(settings, setting_name('TRAILING_SLASH'), True) and '/' or ''

app_name = 'social'

urlpatterns = [
    # authentication / association
    url(r'^(?P<backend>[^/]+){0}$'.format(extra), views.auth,
        name='begin'),
    url(r'^complete/(?P<backend>[^/]+){0}$'.format(extra), views.complete,
        name='complete'),
    # disconnection
    url(r'^disconnect/(?P<backend>[^/]+){0}$'.format(extra), views.disconnect,
        name='disconnect'),
    url(r'^disconnect/(?P<backend>[^/]+)/(?P<association_id>\d+){0}$'
        .format(extra), views.disconnect, name='disconnect_individual'),
]

apps/blog/models.py
from apps.db.base_manager import BaseManager
from apps.db.base_model import BaseModel
import markdown
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension


# Create your models here.


class ClassfiyManager(BaseManager):
    """分类模型管理器类"""

    def get_all_classfiy(self):
        """获取所有文章分类"""
        classfiy_obj_list = self.all()
        if classfiy_obj_list.exists():
            for classfiy_obj in classfiy_obj_list:
                # 给分类增加数量属性
                classfiy_obj.sum = classfiy_obj.article_set.all().filter(classfiy=classfiy_obj.id).count()
            return classfiy_obj_list
        else:
            return None

    def get_classfiy(self, classfiy_id):
        """获取到分类对象"""
        classfiy_obj = self.get_object(id=classfiy_id)
        if classfiy_obj.exists():
            return classfiy_obj[0]
        else:
            return None


class Classfiy(BaseModel):
    """文章分类模型"""
    name = models.CharField(max_length=20, verbose_name='文章分类')

    objects = ClassfiyManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name
        db_table = 'blog_classfiy'


class TagManager(BaseManager):
    """标签模型管理器类"""

    def get_tag_list(self):
        """获取标签列表"""
        tag_obj_list = self.get_list_object()
        if tag_obj_list.exists():
            return tag_obj_list
        else:
            return None

    def get_tags(self, tags_id):
        """获取到分类对象"""
        tag_obj = self.get_object(id=tags_id)
        if tag_obj.exists():
            return tag_obj[0]
        else:
            return None


class Tag(BaseModel):
    """文章标签模型"""
    name = models.CharField(max_length=30, verbose_name='标签')

    objects = TagManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "文章标签"
        verbose_name_plural = verbose_name
        db_table = 'blog_tag'


class ArticleManager(BaseManager):
    """文章模型管理器类"""

    def get_one_article(self, article_id):
        """获取一篇文章"""
        article_obj = self.get_object(id=article_id)
        if article_obj.exists():
            article_obj = article_obj[0]
            article_obj.comment_num = article_obj.comment_set.count  # 增加评论数量属性
            return article_obj
        else:
            return None

    def get_article_list(self, sort='read'):
        """获取文章集合"""
        if sort == 'read':
            sort = ('-read_num',)         # 根据文章阅读量进行排序
        elif sort == 'new':
            sort = ('update_time',)       # 根据文章更新时间进行排序
        article_list = self.get_list_object(filters={}, order_by=sort)
        if article_list.exists():
            for article_obj in article_list:
                article_obj.comment_num = article_obj.comment_set.count  # 增加评论数量属性
            return article_list
        else:
            return None

    def get_html(self, article):
        """得到渲染后的文本"""
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',  # 语法高亮拓展
            TocExtension(slugify=slugify),     # 自动生成目录
        ])
        article.body = md.convert(article.body)  # 将文章渲染成html格式
        article.toc = md.toc  # 文章目录
        return article

    def add_read_num(self, article_id):
        """增加文章阅读量"""
        article_obj = self.get_one_article(article_id=article_id)  # 根据文章id获取到文章
        article_obj.read_num = int(article_obj.read_num) + int(1)
        article_obj.save()

    def get_article_list_by_month(self, year, month):
        """根据月份获取文章集合"""
        article_list = self.get_article_list()  # 获取文章集合
        article_list = article_list.filter(create_time__year=year, create_time__month=month)
        if article_list.exists():
            for article_obj in article_list:
                article_obj.comment_num = article_obj.comment_set.count  # 增加评论数量属性
            return article_list
        else:
            return None

    def get_article_by_tags(self, tags_id):
        """根据标签id或分类id获取文章"""
        article_obj_list = self.get_list_object(filters={'tags': tags_id})
        if article_obj_list.exists():
            for article_obj in article_obj_list:
                article_obj.comment_num = article_obj.comment_set.count  # 增加评论数量属性
            return article_obj_list
        else:
            return None

    def get_article_by_classfiy(self, classfiy_id):
        """根据标签获取文章"""
        article_obj_list = self.get_list_object(filters={'classfiy': classfiy_id})
        if article_obj_list.exists():
            for article_obj in article_obj_list:
                article_obj.comment_num = article_obj.comment_set.count  # 增加评论数量属性
            return article_obj_list
        else:
            return None


class Article(BaseModel):
    """文章模型"""
    title = models.CharField(max_length=100, verbose_name='文章标题')
    body = models.TextField(verbose_name='文章')
    excerpt = models.CharField(max_length=200, blank=True, verbose_name='摘要')
    author = models.ForeignKey(User, verbose_name='作者')
    classfiy = models.ForeignKey(Classfiy, verbose_name='分类')
    read_num = models.PositiveIntegerField(default=0, verbose_name='阅读量')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name='标签')

    objects = ArticleManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        db_table = 'blog_article'


class CommentManager(BaseManager):
    """评论模型管理器类"""

    def get_comment_list(self, article_id):
        """获取评论"""
        comment_list = self.get_list_object(filters={'article_id': article_id}, order_by=('-update_time',))  # 获取最新评论
        if comment_list.exists():
            return comment_list
        else:
            return None

    def create_comment_by_article(self, comment, name, email, addr, article_id):
        """根据文章id添加评论"""
        self.create_one_object(comment=comment, name=name, email=email, addr=addr, article_id=article_id)
        print('create ')


class Comment(BaseModel):
    """评论模型类"""
    comment = models.CharField(max_length=1024, verbose_name='评论')
    name = models.CharField(max_length=30, verbose_name='名字')
    email = models.EmailField(max_length=20, verbose_name='邮箱')
    addr = models.CharField(max_length=40, verbose_name='用户发表评论时的地址')
    article = models.ForeignKey(Article, verbose_name='所属文章')

    objects = CommentManager()

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name
        db_table = 'blog_comment'


class ContatcManager(BaseManager):
    """联系模型管理器类"""

    def create_contatc(self, name, subject, email, message):
        """保存联系"""
        self.create_one_object(name=name, subject=subject, email=email, message=message)


class Contatc(BaseModel):
    """联系模型类"""
    name = models.CharField(max_length=30, verbose_name='姓名')
    subject = models.CharField(max_length=60, verbose_name='主题')
    email = models.EmailField(max_length=20, verbose_name='邮箱')
    message = models.TextField(verbose_name='内容')

    objects = ContatcManager()

    def __str__(self):
        return self.Contatc

    class Meta:
        verbose_name = '联系'
        verbose_name_plural = verbose_name
        db_table = 'blog_Contatc'

apps/blog/views.py
from django.shortcuts import render, redirect
from django.http import response, JsonResponse, HttpResponseRedirect
from .models import Article, Classfiy, Comment, Tag, Contatc
from django.core.paginator import Paginator
from django.views.decorators.cache import cache_page  # 导入缓存装饰器

# Create your views here.


# @cache_page(60 * 5)  # 缓存5分钟
def index(request, pindex):
    """显示首页视图"""
    Article_obj_list = Article.objects.get_article_list(sort='read')  # 获取文章列表
    classfiy_list = Classfiy.objects.get_all_classfiy()               # 获取分类列表
    tags = Tag.objects.get_list_object()                              # 获取标签列表
    # 分页
    if pindex == '':
        pindex = 1
    pindex = int(pindex)
    paginator = Paginator(Article_obj_list, 3)
    # 获取第pindex页内容
    Article_obj_list = paginator.page(pindex)  # 返回pindex页的page实例对象
    # 获取分页后的总数
    nums_pages = paginator.num_pages
    # 控制页码
    pindex = int(pindex)
    if nums_pages < 5:
        # 如果页面不足5页则全部显示
        pages = range(1, nums_pages + 1)
    elif pindex <= 3:
        # 当前页前三页，显示前五页
        pages = range(1, 6)
    elif nums_pages - pindex <= 2:  # 10 9 8 7
        # 当前页是后三页, 显示后五页
        pages = range(nums_pages - 4, nums_pages + 1)
    else:
        # 其他情况,显示当前页的前两页和后两页,当前页
        pages = range(pindex - 2, pindex + 3)
    New_Article_List = Article.objects.get_article_list(sort='new')[:4]      # 获取到最新4篇文章列表
    date_list = Article.objects.dates('create_time', 'month', order='DESC')  # 文章归档
    return render(request, 'blog/index.html', {'Article_obj_list': Article_obj_list,
                                               'Classfiy_List': classfiy_list,
                                               'tags': tags, 'pages': pages,
                                               'New_Article_List': New_Article_List,
                                               'date_list': date_list})


# @cache_page(60 * 5)  # 缓存15分钟
def about(request):
    """关于页面"""
    return render(request, 'blog/about.html')


# @cache_page(60 * 5)  # 缓存15分钟
def blog(request, article_id):
    """博客页面"""
    article = Article.objects.get_one_article(article_id=article_id)  # 通过文章id获取到文章
    article = Article.objects.get_html(article)          # 获取渲染成html的文本
    Article.objects.add_read_num(article_id=article_id)  # 增加文章的阅读量
    comment_list = Comment.objects.get_comment_list(article_id=article_id)     # 根据文章id获取文章所对应的评论
    New_Article_List = Article.objects.get_article_list(sort='new')  # 获取到最新的文章列表
    classfiy_list = Classfiy.objects.get_all_classfiy()  # 获取分类列表
    tags = Tag.objects.get_list_object()  # 获取标签列表
    date_list = Article.objects.dates('create_time', 'month', order='DESC')  # 文章归档
    return render(request, 'blog/detail.html', context={'article': article, 'comment_list': comment_list,
                                                        'New_Article_List': New_Article_List,
                                                        'Classfiy_List': classfiy_list,
                                                        'tags': tags, 'date_list': date_list})


def tidy(request, year, month):
    """根据归档查询显示"""
    article_list = Article.objects.get_article_list_by_month(year=year, month=month)
    return render(request, 'blog/temp.html', context={'article_list': article_list})


def classfiy(request, classfiy_id):
    """根据分类查询"""
    article_list = Article.objects.get_article_by_classfiy(classfiy_id=classfiy_id)  # 通过分类id获取到文章
    title = Classfiy.objects.get_classfiy(classfiy_id=classfiy_id).name
    return render(request, 'blog/temp.html', context={'article_list': article_list, 'title': title})


def tags(request, tags_id):
    """根据标签查询"""
    article_list = Article.objects.get_article_by_tags(tags_id=tags_id)  # 通过标签id获取到文章
    title = Tag.objects.get_tags(tags_id=tags_id).name
    return render(request, 'blog/temp.html', context={'article_list': article_list, 'title': title})


# @cache_page(60 * 5)  # 缓存5分钟
def Contact(request):
    """联系页面"""
    return render(request, 'blog/contact.html')


def contatc_post(request):
    """接收联系数据"""
    name = request.POST.get('name')
    email = request.POST.get('email')
    subject = request.POST.get('subject')
    message = request.POST.get('message')
    Contatc.objects.create_contatc(name=name, email=email, subject=subject, message=message)
    return redirect('/')


def not_found(request):
    """404页面"""
    return render(request, 'error/404.html')

apps/templates/blog/about.html
{% extends 'base.html' %}
{%load static from staticfiles%}
{% block title %}关于{% endblock title %}
{% block body_id %}<body id="page">{% endblock body_id %}
{% block link %}
<link rel="stylesheet" href="{% static 'ALiIcon/iconfont.css' %}">
{% endblock link %}
{% block son %}
<div class="content-body">
		<div class="container">
			<div class="row">
				<main class="col-md-12">
					<h1 class="page-title">关于我</h1>
					<article class="post">
						<div class="entry-content clearfix">
							<figure class="img-responsive-center">
								<img class="img-responsive" src="{% static 'img/me.png' %}" alt="Developer Image">
							</figure>
							<p>Le vent se lève, il faut tenter de vivre</p>
							<p>纵有疾风起 人生不言弃</p>
							<div class="height-40px"></div>
							<h2 class="title text-center">Social</h2>
							<ul class="social">
								<li class="twitter"><a href="https://weibo.com/p/1005055138284214/home?from=page_100505&mod=TAB#place" target="_blank"><span class="iconfont icon-weibo"></span></a></li>
								<li class="twitter"><a href="http://aibeta.oss-cn-beijing.aliyuncs.com/img/QQ.jpg" target="_blank"><span class="iconfont icon-QQ" ></span></a></li>
								<li class="twitter"><a href="http://aibeta.oss-cn-beijing.aliyuncs.com/img/%E5%BE%AE%E4%BF%A1.jpg" target="_blank"><span class="iconfont icon-wechat"></span></a></li>
								<li class="twitter"><a href="https://github.com/LSJOP/Blog" target="_blank"><span class="iconfont ion-social-github"></span></a></li>
							</ul>
						</div>
					</article>
				</main>
			</div>
		</div>
	</div>
{% endblock son %}

apps/templates/blog/contact.html
{% extends 'base.html' %}
{%load static from staticfiles%}
{% block title %}联系{% endblock title %}
{% block body_id %}<body id="page">{% endblock body_id %}



{% block son %}

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">联系</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form class="contact-form" method="post" action="/contatc_post/">
									{% csrf_token %}
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text"  name="name" placeholder="姓名" id="name" required>
											<input type="email" name="email" placeholder="邮箱"  id="email" required>
											<input type="text"  name="subject" placeholder="主题" id="subject" required>
											<textarea name="message" rows="7" placeholder="内容" id="message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane" ><span>给我留言</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

{% endblock son %}

apps/templates/blog/detail.html
{% extends 'base.html' %}
{%load static from staticfiles%}
{% block title %}博客{% endblock title %}
{% block body_id %}<body id="single">{% endblock body_id %}
{% block link %}
<link rel="stylesheet" href="{% static 'ALiIcon/iconfont.css' %}">
{% endblock link %}
{% block son %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ article.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ article.classfiy }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date">{{ article.create_time }}</time></a></span>
                            <span class="post-author"><a href="/about/">{{ article.author }}</a></span>
                            <span class="comments-link"><a href="#">{{ article.comment_num }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ article.read_num }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        {{ article.body|safe }}
                    </div>

                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                      <ul class="social">
                        <li class="twitter"><a href="/user/index/" target="_blank"><span class="iconfont icon-icokite"></span></a></li>
						<li class="twitter"><a href="{% url 'social:begin' 'weibo' %}" target="_blank"><span class="iconfont icon-weibo"></span></a></li>
                      </ul>
                    <h3>发表评论</h3>
                    <form action="/user/comment/{{ article.id }}/" method="post" class="comment-form" >
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name" >名字：</label>
                                <input type="text" id="id_name" name="name" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                <input type="email" id="id_email" name="email" required>
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                <input type="text" id="id_url" name="url">
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                <textarea name="comment" id="id_comment" required></textarea>
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ article.comment_num }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment_obj in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment_obj.name }}</span>
                                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment_obj.update_time }}</time>
                                <div class="text">
                                    {{ comment_obj.comment }}
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            </main>

            <aside class="col-md-4">
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <ul>
                        <a href="">{{ article.toc|safe }}</a>
                    </ul>
                </div>


                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% for article in New_Article_List %}
                        <li>
                            <a href="/blog/{{ article.id }}/">{{ article.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="/tidy/{{ date.year }}/{{ date.month }}/">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% for class in Classfiy_List %}
                            <li>
                                <a href="/classfiy/{{ class.id }}">{{ class.name }}<span class="post-count">({{ class.sum }})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in tags %}
                        <li>
                            <a href="/tags/{{ tag.id }}">{{ tag }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>

        </div>
    </div>
</div>

{% endblock son %}

apps/templates/blog/index.html
{% extends 'base.html' %}
{%load static from staticfiles%}
{% block title %}Black &amp; White{% endblock title %}

{% block son %}
<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% for Article_obj in Article_obj_list %}
                <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="/blog/{{ Article_obj.id }}/">{{ Article_obj.title }}</a>
                        </h1>
                        <div class="entry-meta">
                                <span class="post-category"><a href="/classfiy/{{ Article_obj.classfiy_id }}">{{ Article_obj.classfiy }}</a></span>
                                <span class="post-date"><a href="/blog/{{ Article_obj.id }}/"><time class="entry-date">{{ Article_obj.create_time }}</time></a></span>
                                <span class="post-author"><a href="/about/">{{ Article_obj.author }}</a></span>
                                <span class="comments-link"><a href="/blog/{{ Article_obj.id }}/">{{ Article_obj.comment_num }} 评论</a></span>
                                <span class="views-count"><a href="/blog/{{ Article_obj.id }}/">{{ Article_obj.read_num }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                            <p>{{ Article_obj.excerpt }}</p>
                            <div class="read-more cl-effect-14">
                                <a href="/blog/{{ Article_obj.id }}/" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                </article>
                {% endfor %}

                <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->
                <div class="pagination">
                        <ul>
                            {% if goods.has_previous %}
                                <a href="/{{ Article_obj_list.previous_page_number }}/">&lt;上一页</a>
                            {% endif %}
                        {% for pindex in pages %}
                            {% if pindex == goods.number %}
                            <li><a href="/{{ pindex }}" class="current">{{ pindex }}</a></li>
                            {% else %}
                            <li><a href="/{{ pindex }}" >{{ pindex }}</a></li>
                            {% endif %}
                            {% endfor %}
                         {% if goods.has_next %}
                             <a href="/{{ Article_obj_list.next_page_number }}/">下一页&gt;</a>
                         {% endif %}
                        </ul>
                    </div>
                </main>
    
             <aside class="col-md-4">
                {% block toc %}<!-- 给文章目录的预留块 -->{% endblock toc %}

                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% for article in New_Article_List %}
                        <li>
                            <a href="/blog/{{ article.id }}/">{{ article.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="/tidy/{{ date.year }}/{{ date.month }}/">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% for class in Classfiy_List %}
                            <li>
                                <a href="/classfiy/{{ class.id }}">{{ class.name }}<span class="post-count">({{ class.sum }})</span></a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in tags %}
                        <li>
                            <a href="/tags/{{ tag.id }}">{{ tag }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>


        </div>
    </div>
</div>
{% endblock son %}

apps/templates/blog/temp.html
{% extends 'base.html' %}
{%load static from staticfiles%}
{% block title %}{{ title }}{% endblock title %}
{% block son %}
		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						{% for article in article_list %}
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="#">{{ article.title }}</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">{{ article.classfiy }}</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" >{{ article.create_time }}</time></a></span>
			
									<span class="post-author"><a href="#">{{ article.author }}</a></span>
									<span class="comments-link"><a href="#">{{ article.comment_num }} 评论</a></span>
									<span class="comments-link"><a href="">{{ article.read_num }} 阅读</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>{{ article.excerpt }}</p>
								<div class="read-more cl-effect-14">
									<a href="/blog/{{ article.id }}/" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
								</div>
							</div>
							{% endfor %}
						</article>

					</main>
				</div>
			</div>
		</div>
{% endblock son %}